# Generated by Django 6.0.3 on 2026-03-24 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Ví dụ: "Thạc sĩ ngôn ngữ Anh - 10 năm kinh nghiệm giảng dạy"', max_length=150, verbose_name='Danh hiệu / Chức danh')),
                ('specializations', models.TextField(blank=True, help_text='Comma-separated. Ví dụ: IELTS, Business English, Phonetics', verbose_name='Chuyên môn')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('certifications', models.TextField(blank=True, help_text='Ví dụ: CELTA, DELTA, TESOL, TEFL', verbose_name='Chứng chỉ giảng dạy')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('website_url', models.URLField(blank=True, verbose_name='Website cá nhân')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Kênh YouTube')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Tổng học viên')),
                ('total_courses', models.PositiveIntegerField(default=0, verbose_name='Tổng khoá học')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='Điểm đánh giá TB')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác minh')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác minh')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ giảng viên',
                'verbose_name_plural': 'Hồ sơ giảng viên',
                'db_table': 'instructor_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Dùng để liên hệ hỗ trợ hoặc xác minh tài khoản.', max_length=20, verbose_name='Số điện thoại')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('country', models.CharField(blank=True, default='Vietnam', max_length=100, verbose_name='Quốc gia')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Thành phố / Tỉnh')),
                ('current_level', models.CharField(choices=[('beginner', 'Mới bắt đầu (A1)'), ('elementary', 'Sơ cấp (A2)'), ('intermediate', 'Trung cấp (B1)'), ('upper_intermediate', 'Trên trung cấp (B2)'), ('advanced', 'Nâng cao (C1)'), ('proficient', 'Thành thạo (C2)')], default='beginner', max_length=30, verbose_name='Trình độ hiện tại')),
                ('learning_goal', models.CharField(choices=[('communication', 'Giao tiếp hàng ngày'), ('business', 'Tiếng Anh thương mại'), ('exam', 'Luyện thi (IELTS/TOEIC/…)'), ('academic', 'Tiếng Anh học thuật'), ('travel', 'Du lịch'), ('other', 'Mục tiêu khác')], default='communication', max_length=30, verbose_name='Mục tiêu học tập')),
                ('target_exam', models.CharField(blank=True, help_text='Ví dụ: IELTS 7.0, TOEIC 900, TOEFL iBT 100', max_length=50, verbose_name='Kỳ thi mục tiêu')),
                ('study_hours_per_week', models.PositiveSmallIntegerField(default=0, help_text='Học viên tự khai khi onboarding.', validators=[django.core.validators.MaxValueValidator(168)], verbose_name='Số giờ học/tuần')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Nghề nghiệp')),
                ('education', models.CharField(blank=True, choices=[('high_school', 'THPT'), ('college', 'Cao đẳng'), ('bachelor', 'Đại học'), ('master', 'Thạc sĩ'), ('doctor', 'Tiến sĩ'), ('other', 'Khác')], max_length=50, verbose_name='Trình độ học vấn')),
                ('preferred_language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', max_length=10, verbose_name='Ngôn ngữ giao diện')),
                ('receive_email_notifications', models.BooleanField(default=True, verbose_name='Nhận thông báo email')),
                ('receive_sms_notifications', models.BooleanField(default=False, verbose_name='Nhận thông báo SMS')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hồ sơ học viên',
                'verbose_name_plural': 'Hồ sơ học viên',
                'db_table': 'student_profiles',
            },
        ),
    ]
