# Generated by Django 5.2.12 on 2026-04-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instructorprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='receive_email_notifications',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='receive_sms_notifications',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='study_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='target_exam',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='updated_at',
        ),
    ]
