# Generated by Django 5.2.12 on 2026-04-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_instructorprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_language',
        ),
    ]
