# Generated by Django 5.2.12 on 2026-03-23 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('question_type', models.CharField(choices=[('single', 'Chọn 1 đáp án'), ('multiple', 'Chọn nhiều đáp án'), ('true_false', 'Đúng / Sai')], default='single', max_length=20, verbose_name='Loại câu hỏi')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Điểm')),
                ('explanation', models.TextField(blank=True, verbose_name='Giải thích đáp án')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Câu hỏi',
                'db_table': 'questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500, verbose_name='Nội dung đáp án')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Đáp án đúng')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'verbose_name': 'Đáp án',
                'verbose_name_plural': 'Đáp án',
                'db_table': 'answers',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài kiểm tra')),
                ('description', models.TextField(blank=True, verbose_name='Hướng dẫn')),
                ('pass_score', models.PositiveSmallIntegerField(default=70, verbose_name='Điểm đạt (%)')),
                ('time_limit', models.PositiveSmallIntegerField(default=0, verbose_name='Giới hạn thời gian (phút)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Số lần làm tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson', verbose_name='Bài học')),
            ],
            options={
                'verbose_name': 'Bài kiểm tra',
                'verbose_name_plural': 'Bài kiểm tra',
                'db_table': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Điểm đạt được (%)')),
                ('passed', models.BooleanField(default=False, verbose_name='Đạt')),
                ('answers_snapshot', models.JSONField(default=dict, help_text='{ question_id: [answer_id, ...] }', verbose_name='Snapshot câu trả lời')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu làm')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Nộp bài')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quizzes.quiz')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lần làm bài',
                'verbose_name_plural': 'Lần làm bài',
                'db_table': 'quiz_attempts',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['quiz', 'student'], name='quiz_attemp_quiz_id_ea4f4c_idx')],
            },
        ),
    ]
