# Generated by Django 5.2.12 on 2026-04-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bài kiểm tra', 'verbose_name_plural': 'Bài kiểm tra'},
        ),
    ]
