# Generated by Django 4.2.30 on 2026-05-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Nạp tiền'), ('payment', 'Thanh toán'), ('refund', 'Hoàn tiền'), ('revenue', 'Nhận doanh thu'), ('withdrawal', 'Rút tiền')], max_length=20),
        ),
    ]
