# Generated by Django 4.2.30 on 2026-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallettransaction_tx_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Ví điện tử', 'verbose_name_plural': 'Ví điện tử'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Giao dịch ví', 'verbose_name_plural': 'Giao dịch ví'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yêu cầu rút tiền', 'verbose_name_plural': 'Yêu cầu rút tiền'},
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số dư sau GD'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Mã tham chiếu'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='completed', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'Nạp tiền'), ('payment', 'Thanh toán'), ('refund', 'Hoàn tiền'), ('revenue', 'Nhận doanh thu'), ('withdrawal', 'Rút tiền')], max_length=20, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='Tên chủ tài khoản'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền rút'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_account',
            field=models.CharField(max_length=50, verbose_name='Số tài khoản'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Ngân hàng'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xử lý'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
