# Generated by Django 5.2.12 on 2026-03-23 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Đang học'), ('completed', 'Hoàn thành'), ('refunded', 'Đã hoàn tiền')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Số tiền đã trả')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Khoá học')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Đăng ký khoá học',
                'verbose_name_plural': 'Đăng ký khoá học',
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cert_number', models.CharField(max_length=50, unique=True, verbose_name='Mã chứng chỉ')),
                ('cert_file', models.FileField(blank=True, upload_to='certificates/', verbose_name='File chứng chỉ (PDF)')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày cấp')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='enrollments.enrollment')),
            ],
            options={
                'verbose_name': 'Chứng chỉ',
                'verbose_name_plural': 'Chứng chỉ',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('watch_seconds', models.PositiveIntegerField(default=0, verbose_name='Đã xem (giây)')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='Truy cập lần cuối')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='enrollments.enrollment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Tiến độ học',
                'verbose_name_plural': 'Tiến độ học',
                'db_table': 'progress',
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='enrollments_student_929bef_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'status'], name='enrollments_course__931283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['enrollment', 'is_completed'], name='progress_enrollm_c628bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('enrollment', 'lesson')},
        ),
    ]
