# Generated by Django 5.2.12 on 2026-04-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='watch_seconds',
        ),
    ]
