# Generated by Django 5.2.12 on 2026-04-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_progress_last_accessed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cert_file',
        ),
    ]
