# Generated by Django 5.2.12 on 2026-04-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_remove_certificate_cert_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['id'], 'verbose_name': 'Đăng ký khoá học', 'verbose_name_plural': 'Đăng ký khoá học'},
        ),
    ]
