# Generated by Django 4.2.30 on 2026-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Mã hoàn thành khóa học', 'verbose_name_plural': 'Mã hoàn thành khóa học'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã hoàn thành'),
        ),
    ]
