# Generated by Django 5.2.12 on 2026-03-23 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.category', verbose_name='Danh mục cha')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tên khoá học')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả chi tiết')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='Ảnh bìa')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Học phí (VNĐ)')),
                ('level', models.CharField(choices=[('beginner', 'Cơ bản'), ('intermediate', 'Trung cấp'), ('advanced', 'Nâng cao')], default='beginner', max_length=20, verbose_name='Trình độ')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('review', 'Chờ duyệt'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='Điểm đánh giá TB')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Tổng học viên')),
                ('requirements', models.TextField(blank=True, verbose_name='Yêu cầu đầu vào')),
                ('what_you_learn', models.TextField(blank=True, verbose_name='Học được gì')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xuất bản')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='Danh mục')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Khoá học',
                'verbose_name_plural': 'Khoá học',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], verbose_name='Số sao')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tên chương')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
            options={
                'verbose_name': 'Chương học',
                'verbose_name_plural': 'Chương học',
                'db_table': 'sections',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tên bài học')),
                ('lesson_type', models.CharField(choices=[('video', 'Video bài giảng'), ('article', 'Bài viết'), ('resource', 'Tài nguyên tải về')], default='video', max_length=20, verbose_name='Loại')),
                ('video_url', models.URLField(blank=True, verbose_name='URL video (stream)')),
                ('video_file', models.FileField(blank=True, upload_to='lessons/videos/', verbose_name='File video')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung bài viết (Markdown)')),
                ('attachment', models.FileField(blank=True, upload_to='lessons/attachments/', verbose_name='File tài liệu')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Tên tài liệu')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Cho xem thử miễn phí')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.section')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'db_table': 'lessons',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'published_at'], name='courses_status_7d1705_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'status'], name='courses_instruc_680c73_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'status'], name='courses_categor_e366fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('course', 'student')},
        ),
    ]
