# Generated by Django 6.0.3 on 2026-03-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = không giảm. Ví dụ: 47 → hiển thị badge -47%, giá gốc gạch chân.', verbose_name='Phần trăm giảm giá (%)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Học phí gốc (VNĐ)'),
        ),
    ]
