# Generated by Django 5.2.12 on 2026-03-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
