# Generated by Django 5.2.12 on 2026-04-05 09:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_review_edit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('video', 'Video bài giảng'), ('article', 'Bài viết (Markdown)'), ('resource', 'Tài nguyên tải về')], max_length=20, verbose_name='Loại nội dung')),
                ('order_index', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Cho xem thử miễn phí')),
                ('video_url', models.URLField(blank=True, verbose_name='URL video (stream)')),
                ('video_file', models.FileField(blank=True, upload_to='lessons/videos/', verbose_name='File video')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('content', models.TextField(blank=True, verbose_name='Nội dung Markdown')),
                ('attachment', models.FileField(blank=True, upload_to='lessons/attachments/', verbose_name='File tài liệu')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='Tên tài liệu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Nội dung bài học',
                'verbose_name_plural': 'Nội dung bài học',
                'db_table': 'lesson_contents',
                'ordering': ['order_index'],
            },
        ),
    ]
