# Generated by Django 5.2.12 on 2026-04-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessoncontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonContent',
        ),
    ]
