# Generated by Django 5.2.12 on 2026-04-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_lessoncontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_preview',
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview_article',
            field=models.BooleanField(default=False, verbose_name='Bài viết xem thử'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview_resource',
            field=models.BooleanField(default=False, verbose_name='Tài liệu xem thử'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_preview_video',
            field=models.BooleanField(default=False, verbose_name='Video xem thử'),
        ),
    ]
