# Generated by Django 5.2.12 on 2026-04-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_lesson_is_preview_lesson_is_preview_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_seconds',
        ),
    ]
