# Generated by Django 5.2.12 on 2026-04-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lesson_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_type',
        ),
    ]
