# Generated by Django 5.2.12 on 2026-04-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
