# Generated by Django 5.2.12 on 2026-04-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim ra trang chủ'),
        ),
        migrations.AddField(
            model_name='category',
            name='pin_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Số nhỏ hơn hiển thị trước. Chỉ có tác dụng khi is_pinned=True.', verbose_name='Thứ tự ghim'),
        ),
    ]
