# Generated by Django 5.2.12 on 2026-04-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_category_is_pinned_category_pin_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày ẩn'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Ẩn bình luận'),
        ),
    ]
