# Generated by Django 4.2.30 on 2026-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_review_is_reported_review_report_reason_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
