# Generated by Django 5.2.12 on 2026-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_review_unique_together_review_attempt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
