# Generated by Django 4.2.30 on 2026-04-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_review_report_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('review', 'Chờ duyệt'), ('published', 'Đã xuất bản'), ('archived', 'Đã lưu trữ'), ('archive_requested', 'Yêu cầu lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
