# Generated by Django 5.2.12 on 2026-03-23 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền (VNĐ)')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('method', models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo'), ('stripe', 'Stripe'), ('bank', 'Chuyển khoản'), ('free', 'Miễn phí')], default='vnpay', max_length=20, verbose_name='Phương thức')),
                ('ref_code', models.CharField(max_length=64, unique=True, verbose_name='Mã tham chiếu (gửi gateway)')),
                ('gateway_ref', models.CharField(blank=True, max_length=128, verbose_name='Mã giao dịch (gateway trả về)')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thanh toán lúc')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.course', verbose_name='Khoá học')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='transaction_student_75a6bf_idx'), models.Index(fields=['status', 'paid_at'], name='transaction_status_94533a_idx')],
            },
        ),
    ]
