# Generated by Django 5.2.12 on 2026-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_code',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Mã tham chiếu (gửi gateway)'),
        ),
    ]
