# Generated by Django 5.2.12 on 2026-03-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_reason',
            field=models.TextField(blank=True, verbose_name='Lý do hoàn tiền'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('refund_requested', 'Yêu cầu hoàn tiền'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
