# Generated by Django 5.2.12 on 2026-04-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_reason',
            field=models.TextField(blank=True, default='', verbose_name='Lý do hoàn tiền'),
        ),
    ]
