# Generated by Django 5.2.12 on 2026-04-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_transaction_refund_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_requested_once',
            field=models.BooleanField(default=False, verbose_name='Đã từng yêu cầu hoàn tiền'),
        ),
    ]
