# Generated by Django 5.2.12 on 2026-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_transaction_refund_requested_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refund_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('success', 'Thành công'), ('failed', 'Thất bại'), ('refund_requested', 'Yêu cầu hoàn tiền'), ('refund_approved', 'Admin đã duyệt'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
