# Generated by Django 4.2.30 on 2026-04-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_transaction_refund_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
