# Generated by Django 4.2.30 on 2026-04-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_transaction_refund_requested_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('vnpay', 'VNPay'), ('momo', 'MoMo'), ('stripe', 'Stripe'), ('bank', 'Chuyển khoản'), ('free', 'Miễn phí'), ('wallet', 'Ví điện tử')], default='vnpay', max_length=20, verbose_name='Phương thức'),
        ),
    ]
