export const courses = [
  {
    id: 1,
    title: "React & TypeScript Mastery",
    instructor: "Alex Chen",
    category: "Web Dev",
    level: "Intermediate",
    rating: 4.9,
    students: 12400,
    duration: "28h",
    price: 89,
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400&q=80",
    color: "#7c5cfc",
    progress: 65,
    lessons: 42,
    description: "Master React with TypeScript from fundamentals to advanced patterns. Build real-world apps with hooks, context, and modern tooling.",
    tags: ["React", "TypeScript", "Hooks", "Redux"],
  },
  {
    id: 2,
    title: "UI/UX Design Fundamentals",
    instructor: "Sarah Kim",
    category: "Design",
    level: "Beginner",
    rating: 4.8,
    students: 9800,
    duration: "22h",
    price: 79,
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80",
    color: "#ff6b9d",
    progress: 30,
    lessons: 35,
    description: "Learn the principles of great design. From wireframing to polished interfaces, develop your eye for beautiful, functional UI.",
    tags: ["Figma", "Wireframing", "Prototyping", "Color Theory"],
  },
  {
    id: 3,
    title: "Python for Data Science",
    instructor: "Marcus Johnson",
    category: "Data Science",
    level: "Beginner",
    rating: 4.7,
    students: 18200,
    duration: "35h",
    price: 99,
    image: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&q=80",
    color: "#00d4aa",
    progress: 80,
    lessons: 58,
    description: "Comprehensive Python course covering pandas, numpy, matplotlib, and machine learning fundamentals with real datasets.",
    tags: ["Python", "Pandas", "NumPy", "ML"],
  },
  {
    id: 4,
    title: "Node.js Backend Engineering",
    instructor: "Elena Vasquez",
    category: "Backend",
    level: "Advanced",
    rating: 4.8,
    students: 7600,
    duration: "40h",
    price: 109,
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&q=80",
    color: "#ffb347",
    progress: 0,
    lessons: 64,
    description: "Build scalable backend systems with Node.js, Express, PostgreSQL, Redis, and Docker. Production-ready architecture patterns.",
    tags: ["Node.js", "Express", "PostgreSQL", "Docker"],
  },
  {
    id: 5,
    title: "iOS Development with Swift",
    instructor: "James Park",
    category: "Mobile",
    level: "Intermediate",
    rating: 4.6,
    students: 5400,
    duration: "32h",
    price: 95,
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&q=80",
    color: "#3b82f6",
    progress: 15,
    lessons: 50,
    description: "Create beautiful iOS apps using Swift and SwiftUI. From first screen to App Store submission.",
    tags: ["Swift", "SwiftUI", "Xcode", "iOS"],
  },
  {
    id: 6,
    title: "Machine Learning A-Z",
    instructor: "Dr. Nina Patel",
    category: "AI/ML",
    level: "Advanced",
    rating: 4.9,
    students: 22000,
    duration: "45h",
    price: 119,
    image: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=80",
    color: "#a855f7",
    progress: 0,
    lessons: 72,
    description: "End-to-end ML pipeline: data preprocessing, feature engineering, model training, evaluation, and deployment.",
    tags: ["TensorFlow", "Scikit-learn", "Deep Learning", "NLP"],
  },
];

export const categories = [
  { id: 1, name: "Web Dev", icon: "🌐", count: 340, color: "#7c5cfc" },
  { id: 2, name: "Design", icon: "🎨", count: 215, color: "#ff6b9d" },
  { id: 3, name: "Data Science", icon: "📊", count: 189, color: "#00d4aa" },
  { id: 4, name: "Mobile", icon: "📱", count: 142, color: "#3b82f6" },
  { id: 5, name: "AI/ML", icon: "🤖", count: 98, color: "#a855f7" },
  { id: 6, name: "Backend", icon: "⚙️", count: 276, color: "#ffb347" },
  { id: 7, name: "DevOps", icon: "🚀", count: 134, color: "#f87171" },
  { id: 8, name: "Security", icon: "🔒", count: 87, color: "#4ade80" },
];

export const lessons = [
  { id: 1, title: "Introduction & Setup", duration: "12:30", completed: true, type: "video" },
  { id: 2, title: "Core Concepts Deep Dive", duration: "24:15", completed: true, type: "video" },
  { id: 3, title: "Building Your First Component", duration: "18:45", completed: true, type: "video" },
  { id: 4, title: "State Management Patterns", duration: "32:00", completed: false, type: "video", current: true },
  { id: 5, title: "Quiz: React Fundamentals", duration: "15 min", completed: false, type: "quiz" },
  { id: 6, title: "Advanced Hooks", duration: "28:20", completed: false, type: "video" },
  { id: 7, title: "Context API & Redux", duration: "35:10", completed: false, type: "video" },
  { id: 8, title: "Performance Optimization", duration: "22:45", completed: false, type: "video" },
  { id: 9, title: "Testing with Jest & RTL", duration: "40:00", completed: false, type: "video" },
  { id: 10, title: "Final Project", duration: "Open-ended", completed: false, type: "project" },
];

export const users = [
  { id: 1, name: "Alice Thompson", email: "alice@example.com", role: "Student", courses: 4, joined: "Jan 12, 2025", status: "active" },
  { id: 2, name: "Bob Martinez", email: "bob@example.com", role: "Instructor", courses: 12, joined: "Mar 3, 2024", status: "active" },
  { id: 3, name: "Carol White", email: "carol@example.com", role: "Student", courses: 7, joined: "Nov 20, 2024", status: "active" },
  { id: 4, name: "David Lee", email: "david@example.com", role: "Student", courses: 2, joined: "Feb 8, 2025", status: "inactive" },
  { id: 5, name: "Eva Chen", email: "eva@example.com", role: "Instructor", courses: 8, joined: "Jun 15, 2023", status: "active" },
  { id: 6, name: "Frank Wilson", email: "frank@example.com", role: "Student", courses: 5, joined: "Sep 1, 2024", status: "active" },
  { id: 7, name: "Grace Kim", email: "grace@example.com", role: "Student", courses: 3, joined: "Dec 5, 2024", status: "banned" },
];

export const instructorCourses = [
  { id: 1, title: "React & TypeScript Mastery", students: 12400, rating: 4.9, revenue: 18600, status: "published", lessons: 42 },
  { id: 2, title: "Advanced React Patterns", students: 4200, rating: 4.7, revenue: 7560, status: "published", lessons: 28 },
  { id: 3, title: "Next.js Full Stack", students: 890, rating: 4.8, revenue: 1602, status: "draft", lessons: 15 },
];

export const stats = {
  admin: { totalUsers: 48200, totalCourses: 1240, revenue: 284000, activeToday: 3200 },
  instructor: { totalStudents: 17490, totalCourses: 3, totalRevenue: 27762, avgRating: 4.8 },
  student: { enrolled: 5, completed: 2, hoursLearned: 47, certificates: 2 },
};
